### ISSUE TITLE
IP表识别OS都是windows

### ISSUE THREAD

**Issue by 0xfcryowbk2ca65z** [ring04h/wyportmap#6]
参数没改，-sT -P0 -sV -O --script=banner -p T:
都是：Microsoft Windows 7 or Windows Server 2012 

假如我需要扫描1-65536 端口的话，貌似没有反应。

**Comment by ring04h** [comment]
这个版本没有维护了，我的环境已经替换成了Masscan

**Comment by ring04h** [comment]
扫描65536个端口，很容易会因为服务端不响应造成网络设备间的阻塞

**Comment by 0xfcryowbk2ca65z** [comment]
好吧，wydomain2做得挺好的，准备用用你的wyproxy
